---
# =================================================================
# apply_change.yml
# Runs on: Managed Node (Oracle VM #2)
# Triggered by: Control Node via ansible-playbook
#
# Usage:
#   ansible-playbook apply_change.yml -e "scenario=small_disk"
#   ansible-playbook apply_change.yml -e "scenario=large_disk"
#   ansible-playbook apply_change.yml -e "scenario=cpu_stress"
#   ansible-playbook apply_change.yml -e "scenario=stop_service"
#
# Output: /tmp/change_applied.json
# =================================================================

- name: Apply Change Scenario
  hosts: managed
  gather_facts: yes

  vars:
    scenario: "small_disk"
    temp_small: /tmp/ai_small.bin
    temp_large: /tmp/ai_large.bin
    output_file: /tmp/change_applied.json

  tasks:

    - name: Validate scenario
      fail:
        msg: >
          Unknown scenario '{{ scenario }}'.
          Valid options: small_disk | large_disk | cpu_stress | stop_service
      when: scenario not in ['small_disk', 'large_disk', 'cpu_stress', 'stop_service']

    # ── small_disk: write 50MB → PASS expected ────────────────────
    - name: "[small_disk] Write 50MB temp file to /tmp"
      command: dd if=/dev/zero of={{ temp_small }} bs=1M count=50 status=none
      when: scenario == "small_disk"
      changed_when: true

    # ── large_disk: write 2GB → FAIL expected ────────────────────
    - name: "[large_disk] Write 2GB temp file to /tmp"
      command: dd if=/dev/zero of={{ temp_large }} bs=1M count=2000 status=none
      when: scenario == "large_disk"
      changed_when: true
      async: 300
      poll: 10

    # ── cpu_stress: 4 yes processes → FAIL expected ───────────────
    - name: "[cpu_stress] Spawn 4 CPU stress processes"
      shell: nohup yes > /dev/null 2>&1 & echo $!
      when: scenario == "cpu_stress"
      loop: [1, 2, 3, 4]
      register: cpu_pids_result
      changed_when: true

    - name: "[cpu_stress] Save remote PIDs for cleanup"
      copy:
        dest: /tmp/stress_pids.txt
        content: "{{ cpu_pids_result.results | map(attribute='stdout') | join('\n') }}\n"
      when: scenario == "cpu_stress"

    - name: "[cpu_stress] Wait 5s for load to build"
      pause:
        seconds: 5
      when: scenario == "cpu_stress"

    # ── stop_service: stop chronyd → FAIL expected ───────────────
    - name: "[stop_service] Stop chronyd service"
      systemd:
        name: chronyd
        state: stopped
      become: yes
      when: scenario == "stop_service"
      changed_when: true

    # ── Capture immediate post-change state ───────────────────────
    - name: Get disk percent after change
      shell: df / | tail -1 | awk '{print $5}' | tr -d '%'
      register: post_root_pct
      changed_when: false

    - name: Get /tmp percent after change
      shell: df /tmp | tail -1 | awk '{print $5}' | tr -d '%'
      register: post_tmp_pct
      changed_when: false

    - name: Get load after change
      shell: cat /proc/loadavg | awk '{print $1}'
      register: post_load
      changed_when: false

    # ── Write output JSON ─────────────────────────────────────────
    - name: Write change_applied.json
      copy:
        dest: "{{ output_file }}"
        content: "{{ result | to_nice_json }}"
      vars:
        result:
          scenario: "{{ scenario }}"
          timestamp: "{{ ansible_date_time.iso8601 }}"
          hostname: "{{ ansible_hostname }}"
          expected_verdict: "{{ 'PASS' if scenario == 'small_disk' else 'FAIL' }}"
          immediate_root_pct: "{{ post_root_pct.stdout | int }}"
          immediate_tmp_pct: "{{ post_tmp_pct.stdout | int }}"
          immediate_load_1m: "{{ post_load.stdout | float }}"
          description:
            small_disk: "Wrote 50MB to /tmp — expected PASS"
            large_disk: "Wrote 2GB to /tmp — expected FAIL"
            cpu_stress: "Spawned 4 CPU stress processes — expected FAIL"
            stop_service: "Stopped chronyd service — expected FAIL"

    - name: Print change summary
      debug:
        msg:
          - "=== CHANGE APPLIED ==="
          - "Scenario  : {{ scenario }}"
          - "Expected  : {{ 'PASS' if scenario == 'small_disk' else 'FAIL' }}"
          - "Root Disk : {{ post_root_pct.stdout }}%"
          - "/tmp Disk : {{ post_tmp_pct.stdout }}%"
          - "Load(1m)  : {{ post_load.stdout }}"
