---
# =============================================================
# pre_health_check.yml
# Runs ON: Oracle VM (managed node)
# Triggered BY: GitHub Actions runner (control node)
# Output: /tmp/pre_health.json  → SCP'd back → GHA artifact
# =============================================================

- name: Pre-Change Health Check
  hosts: managed
  gather_facts: yes

  vars:
    output_file: /tmp/pre_health.json
    change_number: "UNKNOWN"

  tasks:

    - name: Get root filesystem usage
      command: df -h /
      register: df_root
      changed_when: false

    - name: Get /tmp filesystem usage
      command: df -h /tmp
      register: df_tmp
      changed_when: false

    - name: Get all filesystems
      command: df -h
      register: df_all
      changed_when: false

    - name: Parse root disk percent
      shell: df / | tail -1 | awk '{print $5}' | tr -d '%'
      register: root_pct
      changed_when: false

    - name: Parse /tmp disk percent
      shell: df /tmp | tail -1 | awk '{print $5}' | tr -d '%'
      register: tmp_pct
      changed_when: false

    - name: Get memory info
      command: free -m
      register: mem_raw
      changed_when: false

    - name: Parse memory used percent
      shell: free | grep Mem | awk '{printf "%.0f", $3/$2 * 100}'
      register: mem_pct
      changed_when: false

    - name: Get load average
      command: cat /proc/loadavg
      register: load_avg
      changed_when: false

    - name: Parse 1-min load
      shell: cat /proc/loadavg | awk '{print $1}'
      register: load_1m
      changed_when: false

    - name: Get CPU count
      command: nproc
      register: cpu_count
      changed_when: false

    - name: Check critical service states
      shell: systemctl is-active {{ item }} 2>/dev/null || echo "inactive"
      register: svc_results
      changed_when: false
      loop:
        - sshd
        - chronyd
        - firewalld
        - auditd

    - name: Get top CPU processes
      shell: ps aux --sort=-%cpu | head -8
      register: top_procs
      changed_when: false

    - name: Get open ports
      shell: ss -tuln | head -20
      register: open_ports
      changed_when: false

    - name: Build warnings list
      set_fact:
        warnings: >-
          {{
            ([] if root_pct.stdout | int <= 80 else ['Root disk at ' + root_pct.stdout + '%']) +
            ([] if tmp_pct.stdout  | int <= 75 else ['/tmp disk at ' + tmp_pct.stdout + '%']) +
            ([] if load_1m.stdout  | float <= 3.0 else ['Load avg ' + load_1m.stdout + ' elevated']) +
            ([] if mem_pct.stdout  | int <= 85 else ['Memory at ' + mem_pct.stdout + '%'])
          }}

    - name: Write pre_health.json
      copy:
        dest: "{{ output_file }}"
        content: "{{ result | to_nice_json }}"
      vars:
        result:
          phase: "PRE"
          change_number: "{{ change_number }}"
          timestamp: "{{ ansible_date_time.iso8601 }}"
          hostname: "{{ ansible_hostname }}"
          kernel: "{{ ansible_kernel }}"
          os: "{{ ansible_distribution }} {{ ansible_distribution_version }}"
          cpu_count: "{{ cpu_count.stdout | int }}"
          load_avg_raw: "{{ load_avg.stdout }}"
          load_1m: "{{ load_1m.stdout | float }}"
          memory:
            raw: "{{ mem_raw.stdout }}"
            used_percent: "{{ mem_pct.stdout | int }}"
          disk:
            root:
              raw: "{{ df_root.stdout }}"
              used_percent: "{{ root_pct.stdout | int }}"
            tmp:
              raw: "{{ df_tmp.stdout }}"
              used_percent: "{{ tmp_pct.stdout | int }}"
            all: "{{ df_all.stdout }}"
          services: "{{ dict(svc_results.results | map(attribute='item') | zip(svc_results.results | map(attribute='stdout'))) }}"
          top_processes: "{{ top_procs.stdout }}"
          open_ports: "{{ open_ports.stdout }}"
          warnings: "{{ warnings }}"

    - name: Print summary
      debug:
        msg:
          - "=== PRE-CHANGE HEALTH CHECK ==="
          - "Change   : {{ change_number }}"
          - "Host     : {{ ansible_hostname }}"
          - "Root     : {{ root_pct.stdout }}%"
          - "/tmp     : {{ tmp_pct.stdout }}%"
          - "Memory   : {{ mem_pct.stdout }}%"
          - "Load(1m) : {{ load_1m.stdout }}"
          - "Warnings : {{ warnings | length }}"
