---
# =================================================================
# pre_health_check.yml
# Runs on: Managed Node (Oracle VM #2)
# Triggered by: Control Node via ansible-playbook
# Output: /tmp/pre_health.json  (read back by engine.py over SSH)
#
# Captures full system health BEFORE the change window opens.
# =================================================================

- name: Pre-Change Health Check
  hosts: managed
  gather_facts: yes

  vars:
    output_file: /tmp/pre_health.json

  tasks:

    # ── Disk ──────────────────────────────────────────────────────
    - name: Get root filesystem usage
      command: df -h /
      register: df_root
      changed_when: false

    - name: Get /tmp filesystem usage
      command: df -h /tmp
      register: df_tmp
      changed_when: false

    - name: Get all filesystems
      command: df -h
      register: df_all
      changed_when: false

    - name: Parse root disk percent
      shell: df / | tail -1 | awk '{print $5}' | tr -d '%'
      register: root_pct
      changed_when: false

    - name: Parse /tmp disk percent
      shell: df /tmp | tail -1 | awk '{print $5}' | tr -d '%'
      register: tmp_pct
      changed_when: false

    # ── Memory ────────────────────────────────────────────────────
    - name: Get memory info
      command: free -m
      register: mem_raw
      changed_when: false

    - name: Parse memory used percent
      shell: free | grep Mem | awk '{printf "%.0f", $3/$2 * 100}'
      register: mem_pct
      changed_when: false

    # ── CPU / Load ────────────────────────────────────────────────
    - name: Get load average
      command: cat /proc/loadavg
      register: load_avg
      changed_when: false

    - name: Parse 1-min load
      shell: cat /proc/loadavg | awk '{print $1}'
      register: load_1m
      changed_when: false

    - name: Get CPU count
      command: nproc
      register: cpu_count
      changed_when: false

    # ── Services ──────────────────────────────────────────────────
    - name: Check critical service states
      shell: systemctl is-active {{ item }} 2>/dev/null || echo "inactive"
      register: svc_results
      changed_when: false
      loop:
        - sshd
        - chronyd
        - firewalld
        - auditd

    # ── Processes ─────────────────────────────────────────────────
    - name: Get top CPU processes
      shell: ps aux --sort=-%cpu | head -8
      register: top_procs
      changed_when: false

    # ── Network ───────────────────────────────────────────────────
    - name: Get open ports
      shell: ss -tuln | head -20
      register: open_ports
      changed_when: false

    # ── Build warnings list ───────────────────────────────────────
    - name: Flag high root disk
      set_fact:
        warnings: "{{ (warnings | default([])) + ['Root disk at ' + root_pct.stdout + '%'] }}"
      when: root_pct.stdout | int > 80

    - name: Flag high /tmp disk
      set_fact:
        warnings: "{{ (warnings | default([])) + ['/tmp disk at ' + tmp_pct.stdout + '%'] }}"
      when: tmp_pct.stdout | int > 75

    - name: Flag high load
      set_fact:
        warnings: "{{ (warnings | default([])) + ['Load avg ' + load_1m.stdout + ' is elevated'] }}"
      when: load_1m.stdout | float > 3.0

    - name: Flag high memory
      set_fact:
        warnings: "{{ (warnings | default([])) + ['Memory usage at ' + mem_pct.stdout + '%'] }}"
      when: mem_pct.stdout | int > 85

    - name: Set empty warnings if none triggered
      set_fact:
        warnings: []
      when: warnings is not defined

    # ── Write JSON output ─────────────────────────────────────────
    - name: Write pre_health.json
      copy:
        dest: "{{ output_file }}"
        content: "{{ result | to_nice_json }}"
      vars:
        result:
          phase: "PRE"
          timestamp: "{{ ansible_date_time.iso8601 }}"
          hostname: "{{ ansible_hostname }}"
          kernel: "{{ ansible_kernel }}"
          os: "{{ ansible_distribution }} {{ ansible_distribution_version }}"
          cpu_count: "{{ cpu_count.stdout | int }}"
          load_avg_raw: "{{ load_avg.stdout }}"
          load_1m: "{{ load_1m.stdout | float }}"
          memory:
            raw: "{{ mem_raw.stdout }}"
            used_percent: "{{ mem_pct.stdout | int }}"
          disk:
            root:
              raw: "{{ df_root.stdout }}"
              used_percent: "{{ root_pct.stdout | int }}"
            tmp:
              raw: "{{ df_tmp.stdout }}"
              used_percent: "{{ tmp_pct.stdout | int }}"
            all: "{{ df_all.stdout }}"
          services: "{{ dict(svc_results.results | map(attribute='item') | zip(svc_results.results | map(attribute='stdout'))) }}"
          top_processes: "{{ top_procs.stdout }}"
          open_ports: "{{ open_ports.stdout }}"
          warnings: "{{ warnings }}"

    - name: Print summary
      debug:
        msg:
          - "=== PRE-CHANGE HEALTH CHECK COMPLETE ==="
          - "Host     : {{ ansible_hostname }}"
          - "Root Disk: {{ root_pct.stdout }}%"
          - "/tmp     : {{ tmp_pct.stdout }}%"
          - "Memory   : {{ mem_pct.stdout }}%"
          - "Load(1m) : {{ load_1m.stdout }}"
          - "Warnings : {{ warnings | length }}"
          - "Output   : {{ output_file }}"
